# Generated by Django 4.2.7 on 2023-11-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_users_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='users_like',
        ),
    ]
