# Generated by Django 4.2.7 on 2023-11-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_quantity_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(default='Ha Noi', max_length=100),
        ),
    ]
