# Generated by Django 4.2.7 on 2023-12-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-total_likes'], name='shop_produc_total_l_785408_idx'),
        ),
    ]
